### ISSUE TITLE
TimeZones Dependency

### ISSUE THREAD

**Issue by ccoffrin** [invenia/Memento.jl#161]
Might it be possible to drop the dependency on TimeZones?  It's build process has been problematic from time to time and it pulls down this file "https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz" which represents non-github hosted data that isn't tracked by the Julia package manager.

**Comment by rofinn** [comment]
I'll redirect this to @omus. I feel like the TimeZones.jl build process should just be fixed. Otherwise, it's a pretty light package... and we do find it helpful to have timezone aware timestamps. There has been a discussion of providing a Minimento.jl (for lack of a better name) package that doesn't have any dependencies, but I think at that point it'd be better to just add the functionality we want to the `Logging` stdlib.

**Comment by omus** [comment]
I've been thinking about using Julia artifacts to store the tzdata which would also address this problem. Out of curiosity, what is problematic about the build process?

**Comment by ccoffrin** [comment]
Over the years it was breaking from time to time, I think the wget/curl call would break due to some proxy issue on my side, which was breaking and fixed at random.

A big advantage of a github-only solution is that the git protocol can be used to pull down all of the data which is friendly with various proxies and filters that I encounter.

**Comment by ccoffrin** [comment]
If Julia artifacts is a viable solution, that sounds good to me!

**Comment by racinmat** [comment]
TimeZones now use Artifacts https://github.com/JuliaTime/TimeZones.jl/releases/tag/v1.3.0

**Comment by rofinn** [comment]
Looks like we should already support that version, so I’ll close this. Please re-open if you run into further issues.

**Comment by ccoffrin** [comment]
Thanks!!!
